# Generated by Django 5.0.13 on 2025-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_key', models.CharField(max_length=255, unique=True)),
                ('order_code', models.CharField(blank=True, max_length=255, null=True)),
                ('po', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('color_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('total_order_qty', models.IntegerField(blank=True, null=True)),
                ('flash', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_po', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=255, null=True)),
                ('hangtag', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap_material', models.CharField(blank=True, max_length=255, null=True)),
                ('skeda', models.CharField(blank=True, max_length=255, null=True)),
                ('no_lines_by_skeda', models.CharField(blank=True, max_length=255, null=True)),
                ('po_new', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id_su', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id_ki', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id_se', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pos',
            },
        ),
    ]
