# Generated by Django 5.0.13 on 2025-04-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_barcoderequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarelabelRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ponum', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carelabel_requests',
            },
        ),
    ]
