# Generated by Django 5.0.13 on 2025-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carelabelrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrowAway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'throw_aways',
            },
        ),
    ]
