# Generated by Django 5.0.13 on 2025-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_throwaway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leftovers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'leftovers',
            },
        ),
    ]
