# Generated by Django 5.0.13 on 2025-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carelabelsestocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('location_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('location_plant', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prep_locations',
            },
        ),
    ]
