# Generated by Django 5.0.13 on 2025-04-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_preplocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequestLabels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('po', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.CharField(blank=True, max_length=255, null=True)),
                ('printer', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'print_request_labels',
            },
        ),
    ]
