# Generated by Django 5.0.13 on 2025-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_leftovers2'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='barcodestocks',
        #     name='qty_waste',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
