# Generated by Django 5.0.13 on 2026-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_barcodestocks_qty_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequestlabels',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
    ]
