# Generated by Django 5.0.13 on 2026-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_composition_to_print_request_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidKIStocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ponum', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('qty_to_receive', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('machine', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfid_ki_stocks',
            },
        ),
        migrations.CreateModel(
            name='RfidRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ponum', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfid_requests',
            },
        ),
        migrations.CreateModel(
            name='RfidSEStocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ponum', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('qty_to_receive', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('machine', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfid_se_stocks',
            },
        ),
        migrations.CreateModel(
            name='RfidStocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ponum', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('machine', models.TextField(blank=True, null=True)),
                ('qty_waste', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfid_stocks',
            },
        ),
    ]
